In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt 
import sklearn 
import xgboost 
from pathlib import Path

In [2]:
path=Path('/home/yazid/agro/1_Traditional_ml/data_fetching')
my_list=[pd.read_csv(df) for df in path.glob('*.csv')]

In [3]:
df=pd.concat(my_list,ignore_index=True)

In [4]:
len(df)

58440

In [5]:
df.head()

,date,temperature_2m_mean,temperature_2m_max,temperature_2m_min,precipitation_sum,rain_sum,precipitation_hours,relative_humidity_2m_mean,surface_pressure_mean,cloud_cover_mean,dew_point_2m_mean,wind_speed_10m_max,wind_gusts_10m_max,wind_direction_10m_dominant,shortwave_radiation_sum,et0_fao_evapotranspiration,city,Unnamed: 0
0,2010-01-01,14.3,17.5,10.7,0.0,0.0,0.0,76,1015.0,40,9.8,13.4,24.8,224,8.61,1.64,Casablanca,NaN
1,2010-01-02,13.4,18.5,9.2,0.0,0.0,0.0,81,1013.7,24,9.9,7.6,19.4,114,12.45,1.87,Casablanca,NaN
2,2010-01-03,15.7,20.7,12.3,0.0,0.0,0.0,77,1013.4,93,11.4,13.6,27.0,195,10.62,2.03,Casablanca,NaN
3,2010-01-04,16.1,19.1,14.5,2.3,2.3,11.0,76,1007.1,41,11.9,29.7,64.4,224,7.84,2.07,Casablanca,NaN
4,2010-01-05,14.6,15.4,13.3,4.0,4.0,14.0,84,1007.5,63,11.9,27.4,64.1,240,6.35,1.43,Casablanca,NaN

In [6]:
df.isna().sum()

date                               0
temperature_2m_mean                0
temperature_2m_max                 0
temperature_2m_min                 0
precipitation_sum                  0
rain_sum                           0
precipitation_hours                0
relative_humidity_2m_mean          0
surface_pressure_mean              0
cloud_cover_mean                   0
dew_point_2m_mean                  0
wind_speed_10m_max                 0
wind_gusts_10m_max                 0
wind_direction_10m_dominant        0
shortwave_radiation_sum            0
et0_fao_evapotranspiration         0
city                               0
Unnamed: 0                     46752
dtype: int64

In [7]:
df.drop('Unnamed: 0',axis=1,inplace=True)

In [8]:
df['date']=pd.to_datetime(df['date'])
df['date'].dtype

dtype('<M8[us]')

In [9]:
df['month']=df['date'].dt.month

Let's do some cyclical encoding on our month values:

In [10]:
df['month_cos']=np.cos(2*np.pi*df['month']/12)
df['month_sin']=np.sin(2*np.pi*df['month']/12)

In [11]:
list(df.columns)

['date',
 'temperature_2m_mean',
 'temperature_2m_max',
 'temperature_2m_min',
 'precipitation_sum',
 'rain_sum',
 'precipitation_hours',
 'relative_humidity_2m_mean',
 'surface_pressure_mean',
 'cloud_cover_mean',
 'dew_point_2m_mean',
 'wind_speed_10m_max',
 'wind_gusts_10m_max',
 'wind_direction_10m_dominant',
 'shortwave_radiation_sum',
 'et0_fao_evapotranspiration',
 'city',
 'month',
 'month_cos',
 'month_sin']

Let's add derived columns:

In [12]:
df['temp_range']=(df['temperature_2m_max']-df['temperature_2m_min'])
df['dew_point_depression']=(df['temperature_2m_mean']-df['dew_point_2m_mean'])
df['win_dir_sin']=np.sin(np.deg2rad(df['wind_direction_10m_dominant']))
df['win_dir_cos']=np.cos(np.deg2rad(df['wind_direction_10m_dominant']))
doy=df['date'].dt.day_of_year
df['doy_sin']=np.sin(2*np.pi*doy/365.25)
df['doy_cos']=np.cos(2*np.pi*doy/365.25)

Let's compute lags

In [13]:
g=df.groupby('city')
for k in (1,3,7):
    df[f'rain_lag_{k}']=g['rain_sum'].shift(k)
df['pressure_change_1d']=g['surface_pressure_mean'].diff()
df['humidity_lag_1']=g['relative_humidity_2m_mean'].shift()

Let's compute rolling columns :

In [14]:
for w in (3,7,30):
    df[f'rain_roll_{w}_sum']=g['rain_sum'].transform(lambda s:s.shift(1).rolling(w).sum())

In [15]:
df=df.sort_values(['city','date'])
test=df.groupby('city',group_keys=False).apply(lambda g:g.tail(int (len(g)*0.2)))
df_train=df.drop(test.index)
df_test=df.loc[test.index]

In [52]:
cols_to_drop=['precipitation_sum', 'precipitation_hours', 'month','date','rain_sum']
df=df.dropna()
df['city']=df['city'].astype('category')

In [53]:
X_train=df_train.drop(cols_to_drop,axis=1)
X_test=df_test.drop(cols_to_drop,axis=1)
y_train=df_train['precipitation_sum']
y_test=df_test['precipitation_sum']
X_train['city']=X_train['city'].astype('category')
X_test['city']=X_test['city'].astype('category')

In [54]:
from xgboost import XGBRegressor
v0=XGBRegressor(n_estimators=600,learning_rate=0.03,max_depth=6,subsample=0.8,colsample_bytree=0.8,enable_categorical=True,
               tree_method='hist')

In [55]:
v0.fit(X_train,y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=True, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.03, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=600,
             n_jobs=None, num_parallel_tree=None, ...)

In [56]:
y_pred_0=v0.predict(X_test)

In [57]:
from sklearn.metrics import mean_absolute_error 
mae_0=mean_absolute_error(y_pred_0,y_test)
(mae_0/y_test.mean())*100

np.float64(75.5694368467072)

Ok nice we got good model but way too many features let's see if we can drop some of them

In [58]:
def get_feature_importance(model,features):
    df_importance=pd.DataFrame({'feature':features,
                              'importance':model.feature_importances_}).sort_values('importance',ascending=False).reset_index(drop=True)
    return df_importance

In [59]:
get_feature_importance(v0,X_train.columns.tolist())

                        feature  importance
0       shortwave_radiation_sum    0.172137
1          dew_point_depression    0.091143
2            wind_gusts_10m_max    0.079672
3                    rain_lag_1    0.074658
4    et0_fao_evapotranspiration    0.061618
5         surface_pressure_mean    0.045021
6              cloud_cover_mean    0.043531
7                          city    0.039292
8            pressure_change_1d    0.033147
9     relative_humidity_2m_mean    0.032154
10                   temp_range    0.031650
11                      doy_cos    0.030377
12           wind_speed_10m_max    0.027298
13               humidity_lag_1    0.022368
14                      doy_sin    0.022032
15              rain_roll_3_sum    0.020727
16            dew_point_2m_mean    0.019504
17                    month_sin    0.018521
18                  win_dir_sin    0.016676
19                    month_cos    0.015116
20  wind_direction_10m_dominant    0.014541
21                  win_dir_cos    0.013769
22           temperature_2m_max    0.013572
23             rain_roll_30_sum    0.012858
24              rain_roll_7_sum    0.012414
25                   rain_lag_3    0.010980
26           temperature_2m_min    0.009436
27                   rain_lag_7    0.009218
28          temperature_2m_mean    0.006570